/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "./features/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#e2e2e2",
        "surface-container-high": "#2a2a2a",
        "primary-container": "#fde400",
        tertiary: "#ffffff",
        "on-primary-fixed": "#201c00",
        "error-container": "#93000a",
        "border-subtle": "#3D3D3D",
        "surface-variant": "#353534",
        surface: "#131313",
        "surface-container-lowest": "#0e0e0e",
        "on-tertiary-fixed-variant": "#454747",
        error: "#ffb4ab",
        "on-secondary-container": "#332900",
        "primary-fixed-dim": "#dec800",
        "surface-dim": "#131313",
        "success-emerald": "#00E676",
        "surface-container": "#201f1f",
        "secondary-container": "#aa8f1c",
        "surface-card": "#2A2A2A",
        background: "#131313",
        "outline-variant": "#4b4731",
        "on-background": "#e5e2e1",
        "on-surface": "#e5e2e1",
        "surface-elevated": "#333333",
        "primary-fixed": "#fde400",
        "on-tertiary-container": "#636565",
        "on-secondary-fixed-variant": "#554500",
        primary: "#ffffff",
        secondary: "#e4c450",
        "on-surface-variant": "#cdc7aa",
        "surface-bright": "#393939",
        "secondary-fixed-dim": "#e4c450",
        "surface-container-low": "#1c1b1b",
        "on-primary-container": "#716500",
        "on-primary": "#373100",
        "tertiary-fixed-dim": "#c6c6c7",
        "surface-tint": "#dec800",
        "secondary-fixed": "#ffe176",
        "on-tertiary-fixed": "#1a1c1c",
        "inverse-surface": "#e5e2e1",
        "tertiary-fixed": "#e2e2e2",
        "on-secondary": "#3b2f00",
        "inverse-primary": "#6a5f00",
        "on-secondary-fixed": "#231b00",
        "on-tertiary": "#2f3131",
        "on-error": "#690005",
        "inverse-on-surface": "#313030",
        "danger-crimson": "#FF1744",
        "on-primary-fixed-variant": "#504700",
        "on-error-container": "#ffdad6",
        "surface-container-highest": "#353534",
        outline: "#979177",
      },
      borderRadius: {
        DEFAULT: "2px",
        lg: "4px",
        xl: "8px",
        full: "9999px",
      },
      spacing: {
        "container-padding-mobile": "16px",
        "section-gap": "32px",
        "container-padding-desktop": "32px",
        "stack-gap": "12px",
        base: "8px",
      },
      fontFamily: {
        "special-gothic": ["SpecialGothicExpandedOne_400Regular"],
        "numeric-data": ["ArchivoNarrow_700Bold"],
        "display-lg": ["ArchivoNarrow_700Bold"],
        "body-md": ["Inter_400Regular"],
        "headline-lg-mobile": ["ArchivoNarrow_700Bold"],
        "headline-md": ["ArchivoNarrow_600SemiBold"],
        "headline-lg": ["ArchivoNarrow_700Bold"],
        "body-lg": ["Inter_400Regular"],
        "label-md": ["Inter_600SemiBold"],
      },
      fontSize: {
        "numeric-data": ["20px", { lineHeight: "24px" }],
        "display-lg": ["48px", { lineHeight: "52px", letterSpacing: "-0.96px" }],
        "body-md": ["16px", { lineHeight: "24px" }],
        "headline-lg-mobile": ["28px", { lineHeight: "34px" }],
        "headline-md": ["24px", { lineHeight: "32px" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.32px" }],
        "body-lg": ["18px", { lineHeight: "28px" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.7px" }],
      },
    },
  },
};
